sudo : required
addons:
  chrome: stable
language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - ng test mat-icon-import
 - ng test ng-d3plot

before_script:
  - npm install -g @angular/cli